version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - ENV KC_DB=mysql
      - ENV KC_DB_URL=jdbc:mysql://mysql:33060/keycloak
      - ENV KC_DB_USERNAME=root
      - ENV KC_DB_PASSWORD=root
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33060:33060"
