version: '3.9'

services:
# Service de Banco de Dados My SQL
 keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    ports:
      - 8080:8080
    environment:
    # User and Password for the Administation Console
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=mysql
      - DB_ADDR=db
      - DB_PORT=3306
    # Same values as the mysql service
      - DB_PASSWORD=049222Xp12
      - DB_DATABASE=keycloakdb
      - PROXY?ADDRESS_FORWARDING=true

     #- ENV KC_DB=mysql
     #- ENV KC_DB_URL=jdbc:mysql://db:3306/keycloak
     #- ENV KC_DB_USERNAME=root
     #- ENV KC_DB_PASSWORD=root    
    depends_on:
      db:
        condition: service_healthy
    networks:
     - keycloak-and-mysql-network
 


# Service de Banco de Dados My SQL
 db:
    container_name: mysql-debian
    image: mysql:8.0.30-debian
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: keycloakdb      
      MYSQL_ROOT_PASSWORD: 049222Xp12
    security_opt:
      - seccomp:unconfined
    networks:
     - keycloak-and-mysql-network
      

    healthcheck:
     test: ["CMD", "mysqladmin","ping","-h","localhost"]
     interval: 10s
     timeout: 10s
     retries: 3

networks:
  keycloak-and-mysql-network:

volumes:
  keycloak-and-mysql-volume: